[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tank-lab-to-nwb"
# dynamic = ["version"]
"version" = "0.4.0"
description = "NWB conversion scripts and tutorials."
readme = "README.md"
license = "MIT"
authors = [
    { name = "Luiz Tauffer", email = "ben.dichter@gmail.com" },
    { name = "Cody Baker Szonja Weigl" },
    { name = "and Ben Dichter" },
]
dependencies = [
    "h5py",
    "hdmf>=4",
    "ipywidgets",
    "isodate",
    "ndx-tank-metadata",
    "neuroconv[spikeglx,kilosort,openephys]",
    "notebook",
    "numpy",
    "nwbwidgets",
    "pynwb>=3",
    "spikeinterface>=0.102.1",
]

requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/catalystneuro/tank-lab-to-nwb"

# [tool.hatch.version]
# path = "tank_lab_to_nwb/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/tank_lab_to_nwb",
]

[tool.ruff]
# Allow lines to be as long as 120.
line-length = 120

[tool.ruff.lint]
select = ["NPY201"]

[tool.uv.sources]
ndx-tank-metadata = { path = "../ndx-tank-metadata", editable = true }
