[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tank-lab-to-nwb"
# dynamic = ["version"]
"version" = "0.4.0"
description = "NWB conversion scripts and tutorials."
readme = "README.md"
license = "MIT"
authors = [
    { name = "Luiz Tauffer", email = "ben.dichter@gmail.com" },
    { name = "Cody Baker Szonja Weigl" },
    { name = "and Ben Dichter" },
]
dependencies = [
    "h5py",
    "hdmf>=4",
    "ipywidgets",
    "isodate",
    "ndx-tank-metadata>=0.2.0",
    "neuroconv[kilosort,openephys,spikeglx]",
    "notebook",
    "numpy",
    "nwbwidgets",
    "pynwb>=3",
    "spikeinterface>=0.102.1",
    "u19-pipeline[pipeline]",
]

requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/catalystneuro/tank-lab-to-nwb"

# [tool.hatch.version]
# path = "tank_lab_to_nwb/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/tank_lab_to_nwb",
]

[tool.ruff]
# Allow lines to be as long as 120.
line-length = 120

[tool.ruff.lint]
select = ["NPY201"]

[dependency-groups]
dev = [
    "datajoint>=0.14.3",
    "plotly>=5.13.1",
    "pynapple>=0.9.2",
    "pytest>=8.4.1",
    "ruff>=0.11.2",
    "setuptools>=75.8.2",
]


[tool.pytest.ini_options]
addopts = "--doctest-modules"
testpaths = ["tests"]

[tool.uv.sources]
ndx-tank-metadata = { path = "../ndx-tank-metadata-clean", editable = true }
u19-pipeline = { path = "../U19-pipeline_python", editable = true }

